### ISSUE TITLE
can we show only a part of video

### ISSUE THREAD

**Issue by pawaom** [AB1209/VideoInShape#1]
can we show only a part of video

suppose a video is 1024*720 

and we want to show in rectangle of 300*200*150*150 

ie from the 300 px  and so on

**Comment by AB1209** [comment]
Yes, it can be done. Check the cropRect() method.

**Comment by pawaom** [comment]
can you share an example how to do it, I am new to android 

this is what I want

Original video

![download (1)](https://user-images.githubusercontent.com/28686824/87560220-da8b0180-c6d8-11ea-99c3-79690436747f.jpg)

what I want 

![Capturebunny](https://user-images.githubusercontent.com/28686824/87560295-ec6ca480-c6d8-11ea-951a-738d1762a97d.PNG)

**Comment by AB1209** [comment]
If you are following demo code, in CropVideoActivity.java check the setVideoLayout(), a method is called to change the shape to a rectangle, videoView.cropRect(0, 0, width, height). Here you can pass your starting coordinates with width and height. 
So in your example video it can start from the coordinates just before the ears of the bunny and width and height of it.
Say ears start from 300, 200 so method should be videoView.cropRect(300, 200, width, height).

**Comment by pawaom** [comment]
thanks , can we show the preview in scaled form, like the cropped version is 300 X 400, the original video was 1024 X 720

can we show a preview of the (300 X 400) as (1024 X 720)  like in the image that i have shared , show the bunny as full video of 1024 X 720

**Comment by AB1209** [comment]
Not sure if I understood it correctly.

If we are looking to show the cropped version (300x400) to the original size then it will stretch and won't look good.

**Comment by pawaom** [comment]
yes i want to stretch it to the original size how can that be done

**Comment by AB1209** [comment]
Actually, that is not supported in this demo.
